[project]
name = "jitcu"
version = "0.0.0"
description = "A Simple Jit for cuda kernel"
requires-python = ">=3.10"
readme = "README.md"
dependencies = [
  "torch",
  "numpy",

  # for profiler
  "tg4perfetto",
  "protobuf == 4.25.8",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.optional-dependencies]
dev = ["pytest", "pre-commit"]

[tool.setuptools]
packages = ["jitcu"]

[tool.setuptools.package-dir]
"jitcu" = "jitcu"

[tool.setuptools.package-data]
"jitcu" = ["data/**"]
